### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by ugultopu** [yooceii/AIBird#3]
# Steps to Reproduce
1. Clone the repository.
2. Edit 'limit_parameter2.txt' to have the following content:
```
y,1

0,4.0

2.0
```
3. Run `python baseline.py`.

The program is exiting with the following error after a couple seconds:

```
Traceback (most recent call last):
  File "baseline.py", line 1260, in <module>
    structures = generate(m_height)
  File "baseline.py", line 367, in generate
    position, child.point)-child.point), position == x1, check_overlap(child, parent_node), '\n')
  File "baseline.py", line 1189, in height_limit
    return min(list(filter(lambda x: x >= point, solve(px-position, y))))
ValueError: min() arg is an empty sequence
```

**Comment by yooceii** [comment]
Is that parameter a triangle? If it is, u should write the whole piecewise function for left part (the area where x <= 2 in ur parameter). And the second part is the y limit, u need to change it as well.
